Logics Modified.! Othello Running fine.
amishas157/reversi-react-electron pull request #1
Opened 2018-03-29 19:13 UTC by sujithTSR

TODO: Winning cases when all empty spaces are not filled, are to be added.

2018-03-30 10:25 UTC, amishas157 commented on src/index.js
> +    if (getDirectionIndex(direction, i, j) === null){
Think that this condition is being handled by https://github.com/amishas157/reversi-react-electron/pull/1/files#diff-1fdf421c05c1140f6d71444ea2b27638R214

```
 if (i && j && squares[i][j] === player) {
```

If either of `i` or `j` is `null`, `[]` will be returned

2018-03-30 10:36 UTC, amishas157 commented on src/index.js
> +    const reverseElements = [];
Whoops, didn't really understand this part. Can you explain a bit?

2018-03-30 10:42 UTC, amishas157 commented on src/index.js
> +      if (squares[i_iter][j_iter] !== null && squares[i_iter][j_iter] !== 'X' ){
Might need to change this condition 
from `squares[i_iter][j_iter] !== 'X'`
to `squares[i_iter][j_iter] === 'X'`

That's why it is giving reverse scores 😛. Same for next condition

2018-03-30 10:44 UTC, amishas157 commented on src/index.js
> +  // Winner can be calculated with the one having more number of places
Yes, right. This was a winner logic from tic-tac-toe and therefore should be changed. Copy pasta. :D

2018-03-30 10:47 UTC, amishas157 requested changes
Looks great to me. Thanks for it 🙇‍♀️ . Also, left some comments and questions, once addressed, let's merge this.

2018-04-08 09:49 UTC, merged

2018-04-08 09:50 UTC, amishas157 commented
Yay 🤗

2018-04-08 10:24 UTC, sujithTSR commented
Great.. (y)

On Sun, Apr 8, 2018 at 3:20 PM, Amisha Singla <notifications@github.com>
wrote:

> Yay 🤗
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/amishas157/reversi-react-electron/pull/1#issuecomment-379536910>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ALPHkwo7GBtmvY-uV8sasnw-AAnvXF-8ks5tmd1bgaJpZM4TA18g>
> .
>